### ISSUE TITLE
Not working with Ionic 3

### ISSUE THREAD

**Issue by erperejildo** [pushandplay/cordova-plugin-apprate#184]
I followed this tutorial: http://ionicframework.com/docs/native/app-rate/

I'm using the second approach but I get this error:
```
Uncaught (in promise): TypeError: Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at Function.Locales.getLocale (http://192.168.1.2:8100/plugins/cordova-plugin-apprate/www/locales.js:53:74)
    at showDialog (http://192.168.1.2:8100/plugins/cordova-plugin-apprate/www/AppRate.js:91:29)
    at Function.AppRate.promptForRating (http://192.168.1.2:8100/plugins/cordova-plugin-apprate/www/AppRate.js:203:7)
    at callCordovaPlugin (http://192.168.1.2:8100/build/vendor.js:77234:43)
    at http://192.168.1.2:8100/build/vendor.js:77260:28
    at http://192.168.1.2:8100/build/vendor.js:58635:17
    at new t (http://192.168.1.2:8100/build/polyfills.js:3:20886)
    at tryNativePromise (http://192.168.1.2:8100/build/vendor.js:58634:20)
    at getPromise (http://192.168.1.2:8100/build/vendor.js:58642:12)
    at wrapPromise (http://192.168.1.2:8100/build/vendor.js:77243:78)
```

If I remove this line I don't trigger the rating but nothing else fails:
`this.appRate.promptForRating(true);`

**Comment by erperejildo** [comment]
no ideas?

**Comment by ldinatale1182** [comment]
I'm using Ionic 3 and have no issues. I followed this tutorial:
http://masteringionic.com/blog/2017-06-20-implementing-the-app-rate-plugin-for-ionic-applications/

**Comment by erperejildo** [comment]
I tried it and same thing. 

There is no too much different comparing with Ionic's one.

The only thing I do in a different way is the injection, because I don't need an extra provider because I want to load this from my component directly so I don't use `@Injectable()`
But anyway Ionic doesn't suggest this either os his documentation.

Might be related? I think it should be something else

**Comment by erperejildo** [comment]
And also what do we need the http injection for? It's not being used

**Comment by erperejildo** [comment]
Ok, working with this tutorial:
https://ionicacademy.com/rate-my-app-ionic/

**Comment by Sampath-Lokuge** [comment]
Thanks. It is working fine now :) @erperejildo

**Comment by DioNNiS** [comment]
This issue happens when customLocale not provided.
Be careful assigning AppRate.preferences = {...}. It's overwriting default preferences. It's better to extend object...
