### ISSUE TITLE
Plugin fails to install when using cordova 7.0.1

### ISSUE THREAD

**Issue by ldinatale1182** [pushandplay/cordova-plugin-apprate#189]
This plugin does not work on Cordova 7.0.1. Downgrading to Cordova 6.5.0 works fine.

```
Failed to install 'cordova-plugin-apprate': Error
    at new PluginInfo (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/src/PluginInfo/PluginInfo.js:355:15)
    at PluginInfoProvider.get (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/src/PluginInfo/PluginInfoProvider.js:35:32)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:209:47
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:816:13)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
Failed to restore plugin "cordova-plugin-apprate" from config.xml. You might need to try adding it again. Error: Cannot find 
```

**Comment by fdambrosio** [comment]
I can't install this plugin: 


```
ionic cordova plugin add cordova-plugin-apprate

Error: Failed to fetch plugin cordova-plugin-apprate via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

```

after that, if iI retry the second time: 

```
ionic cordova plugin add cordova-plugin-apprate

Error: Cannot find plugin.xml for plugin "yargs-parser"
```

the third time was good: 

```
ionic cordova plugin add cordova-plugin-apprate

Installing "cordova-plugin-apprate" for ios
Installing "cordova-plugin-dialogs" for ios
Installing "cordova-plugin-globalization" for ios
Installing "cordova-plugin-inappbrowser" for ios

Cross-platform AppRate plugin for Cordova / PhoneGap
Adding cordova-plugin-apprate to package.json
Saved plugin info for "cordova-plugin-apprate" to config.xml
```
