### ISSUE TITLE
Ionic 4 + App rate Plugin Not working 

### ISSUE THREAD

**Issue by jagan27101986** [pushandplay/cordova-plugin-apprate#257]
E/Capacitor/Console: File: http://localhost/vendor.js - Line 51847 - Msg: ERROR Error: Uncaught (in promise): ReferenceError: NativeStorage is not defined
    ReferenceError: NativeStorage is not defined
        at capacitor-runtime.js:3491:7
        at new Promise (<anonymous>)
        at Object.get (capacitor-runtime.js:3490:12)
        at Function.AppRate.init (capacitor-runtime.js:2891:15)
        at capacitor-runtime.js:3003:9
        at build (capacitor-runtime.js:1015:13)
        at require (capacitor-runtime.js:1030:28)
        at localRequire (capacitor-runtime.js:1011:24)
        at Object.exports.mapModules (capacitor-runtime.js:2239:30)
        at capacitor-runtime.js:2163:26

Though it mentions that the issue has been fixed with capacitor. When i try running the same in Android, the error is mentioned as above. 
Could you please help me out how to fix it .
I am using Ionic Version   "@ionic-native/app-rate": "^5.15.1","@ionic-native/native-storage": "^5.14.0"

**Comment by CFT-Chris** [comment]
I encountered this issue, and fixed it by running the Capacitor CLI command:

`npx cap sync android`

This detected cordova-plugin-nativestorage as a missing dependency and installed it.  Upon inspection NativeStorage is now defined at the window level and AppRate no longer fails.
